name: Predictive Model Pipeline

on:
  workflow_run:
    workflows: ["Predictive Model Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt dvc
          pip install matplotlib scikit-learn mlflow tensorflow tf2onnx 

      - name: Build Docker image for API
        run: docker build -f Dockerfile -t api .

      - name: Build Docker image for Interface
        run: docker build -f Dockerfile1 -t vmesnik .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image for API
        run: docker tag api:latest ${DOCKER_USERNAME}/api:latest && docker push ${DOCKER_USERNAME}/api:latest

      - name: Push Docker image for Interface
        run: docker tag vmesnik:latest ${DOCKER_USERNAME}/vmesnik:latest && docker push ${DOCKER_USERNAME}/vmesnik:latest

      - name: Deploy to Koyeb
        run: |
          koyeb service update api-service \
            --docker ${DOCKER_USERNAME}/api:latest \
            --token ${KOYEB_API_TOKEN}
          koyeb service update interface-service \
            --docker ${DOCKER_USERNAME}/vmesnik:latest \
            --token ${KOYEB_API_TOKEN}
        env:
          KOYEB_API_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
