name: Predictive Model Pipeline

on:
  workflow_run:
    workflows: ["Predictive Model Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt dvc
          pip install matplotlib scikit-learn mlflow tensorflow tf2onnx 

      
      - name: Ovrednotenje
        run: ovrednotenje_modela.py

      
